### ISSUE TITLE
Wardrobe: Hands Module Forgetting Previous Users

### ISSUE THREAD

**Issue by Jordach** [Jordach/Solar_Plains#7]
This only occurs if user a logs in, then the server restarts.

When, once user b logs in, and user a does not, the mod storage is updated with *only* user b's wardrobe data.

After the server restarts, user a is given the stock Sam II arm, while user b has their custom wardrobe data.

My suggested fix is to deserialize the saved data from mod storage and load that into memory before any user joins the server, that way, data is kept between server instances.

**Comment by benrob0329** [comment]
Each user's hand texture should be stored separately, rather than in one big pile. A function like ``wardrobe.get_hand(name)`` would work.

Something like:
```Lua
function wardrobe.get_hand(name)
    local hand = mod_storage:get_string("wardrobe:"..name..":hand")

    if (hand) then
        return hand
    else
        return "default_hand.png"
    end
end
````
